name: App CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: 'Setup Node.js'
        with:
          node-version: '22'
      - run: npm install --global yarn
        name: 'Setup Yarn'
      - run: cd $GITHUB_WORKSPACE/src/leaderboards-app && yarn
        name: 'Install Dependencies'
      - run: cd $GITHUB_WORKSPACE/src/leaderboards-app && yarn build
        name: 'Build'
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: $GITHUB_WORKSPACE/src/leaderboards-app/dist

  deploy_test_job:
    runs-on: ubuntu-latest
    name: Deploy Test
    needs: build_job
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Deploy Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_SKY_0C3E75503 }}
          action: "upload"
          skip_app_build: true
          output_location: "dist"

  deploy_prod_job:
    runs-on: ubuntu-latest
    name: Deploy Prod
    needs: deploy_test_job
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_SKY_0C3E75503 }}
          action: "upload"
          skip_app_build: true
          output_location: "dist"
